package utilities.enums;

public enum Keyword {
    SELECT, MIN, MAX, AVG, COUNT, SUM, FROM, JOIN, USING, WHERE, AND, OR,
    CREATE, TABLE, NUMBER, CHAR, DROP, INSERT, INTO, VALUES, DELETE, UPDATE,
    SET, GRANT, ALTER, INDEX, REFERENCES, ALL, PRIVILEGES, TO, REVOKE, ON
}
